// Daily motivational quotes - selected deterministically by day of year
export const QUOTES: string[] = [
  "A disciplina vence o talento quando o talento não tem disciplina.",
  "Você não precisa ser extremo, só precisa ser consistente.",
  "Um dia de cada vez. Uma escolha de cada vez.",
  "O corpo conquista o que a mente acredita.",
  "Pequenos passos diários superam grandes saltos esporádicos.",
  "Seu único concorrente é quem você foi ontem.",
  "Quando quiser desistir, lembre por que começou.",
  "Suor de hoje, orgulho de amanhã.",
  "O progresso é silencioso. Continue.",
  "Treinar é votar na pessoa que você quer se tornar.",
  "Você é mais forte do que sua desculpa favorita.",
  "Hidrate, durma, treine, repita.",
  "Não pare quando estiver cansado. Pare quando terminar.",
  "Constância é mais valiosa do que intensidade.",
  "O melhor momento para começar foi ontem. O segundo melhor é agora.",
  "Sua saúde é o investimento com o maior retorno da vida.",
  "Mente forte constrói corpo forte.",
  "Não conte os dias, faça os dias contarem.",
  "Cada repetição te aproxima do seu objetivo.",
  "Comece devagar, mas nunca pare.",
  "O sucesso é a soma de pequenos esforços repetidos.",
  "Você não falha quando cai. Falha quando não levanta.",
  "Dor é fraqueza saindo do corpo.",
  "A jornada é tão importante quanto o destino.",
  "Decida hoje quem você quer ser amanhã.",
  "Cuidar de si é um ato de poder, não de luxo.",
  "Compare-se apenas com o seu eu de ontem.",
  "Pequenos hábitos. Grandes resultados.",
  "O treino acaba, o orgulho fica.",
  "Comece. O resto é consequência.",
  "Energia atrai energia. Mexa-se.",
  "Quem cuida do corpo cuida do futuro.",
  "Você está sempre a um treino do bom humor.",
  "Vontade é o que te leva. Hábito é o que te mantém.",
  "Foque no processo, o resultado vem.",
  "Cada copo d'água é uma vitória.",
  "Descanso também é treino.",
  "Sem desculpas. Só ação.",
  "Você não precisa ser perfeito. Precisa ser presente.",
  "Saúde se constrói no detalhe, não no extremo.",
  "Respire fundo. Você consegue.",
  "Acredite no processo, mesmo nos dias difíceis.",
  "Quem persiste, conquista.",
  "Hoje é um ótimo dia para começar de novo.",
  "Seu futuro eu vai te agradecer por hoje.",
  "Confie no plano. Faça sua parte.",
  "Coma para nutrir, não para preencher.",
  "Movimento é remédio.",
  "O melhor exercício é o que você consegue manter.",
  "Pequenas vitórias todos os dias = grande transformação.",
  "Você está construindo algo maior do que vê.",
  "Não existe milagre, existe método.",
  "Levantar 1% melhor a cada dia já é vitória.",
  "Dê o seu melhor hoje. Amanhã se preocupa amanhã.",
  "Você é capaz de mais do que imagina.",
  "Seu corpo é seu templo. Cuide com carinho.",
  "Saúde é riqueza silenciosa.",
  "Treinar é se respeitar.",
  "A motivação te começa. O hábito te leva longe.",
  "Continue. Você está mais perto do que pensa.",
];

export const TIPS: string[] = [
  "Beba um copo d'água assim que acordar — acelera o metabolismo.",
  "Inclua proteína em todas as refeições para melhor saciedade.",
  "Mastigue devagar: ajuda na digestão e no controle do apetite.",
  "Folhas verdes escuras são ricas em ferro e antioxidantes.",
  "Evite líquidos durante as refeições; prefira 30 min antes ou depois.",
  "Carboidratos antes do treino dão energia para render mais.",
  "Pós-treino: combine proteína + carboidrato para melhor recuperação.",
  "Frutas vermelhas ajudam na recuperação muscular.",
  "Ovos são uma das proteínas mais completas e econômicas.",
  "Castanhas com moderação: gordura boa e saciedade.",
  "Reduza ultraprocessados. Quanto menos ingrediente, melhor.",
  "Cozinhe em casa: você controla sal, açúcar e óleo.",
  "Tempere com ervas frescas em vez de molhos industriais.",
  "Azeite de oliva extravirgem cru é melhor para o coração.",
  "Sono ruim atrapalha emagrecimento. Priorize 7-9h.",
  "Caminhar 20 min após refeições ajuda no controle glicêmico.",
  "Tenha água sempre à vista — você bebe mais sem perceber.",
  "Substitua refrigerante por água com gás + limão.",
  "Iogurte natural + frutas: lanche perfeito.",
  "Aveia regula intestino e dá saciedade prolongada.",
  "Coma o arco-íris: variedade de cores = variedade de nutrientes.",
  "Planeje refeições no domingo para a semana toda.",
  "Não pule café da manhã se você treina pela manhã.",
  "Açúcar refinado vicia. Reduza aos poucos.",
  "Peixes 2x na semana melhoram saúde do coração.",
  "Feijão é proteína vegetal acessível e completa com arroz.",
  "Ovos cozidos são lanche pronto, prático e nutritivo.",
  "Banana antes do treino: energia rápida + potássio.",
  "Whey protein é prático, mas não substitui comida real.",
  "Beba água antes de sentir sede; sede já é desidratação leve.",
  "Reduza álcool: atrapalha sono, recuperação e hipertrofia.",
  "Café antes do treino pode aumentar performance.",
  "Vitamina D vem do sol — tome 15 min/dia de manhã.",
  "Magnésio (folhas verdes, castanhas) ajuda no sono.",
  "Salada antes do prato principal reduz pico glicêmico.",
  "Lanche da tarde: mix de proteína + fibra evita beliscar.",
  "Evite comer assistindo TV: leva a comer mais.",
  "Coma sentado, com calma. Saciedade chega em 20 min.",
  "Doce ocasional: ok. Doce diário: revise.",
  "Hidratação é treino também: 30-40 ml/kg de peso por dia.",
];

export function quoteOfDay(date = new Date()): string {
  const start = new Date(date.getFullYear(), 0, 0);
  const day = Math.floor((date.getTime() - start.getTime()) / 86400000);
  return QUOTES[day % QUOTES.length];
}

export function tipOfDay(date = new Date()): string {
  const start = new Date(date.getFullYear(), 0, 0);
  const day = Math.floor((date.getTime() - start.getTime()) / 86400000);
  return TIPS[day % TIPS.length];
}
